Increase RSA key size for PyPy3
The PyPy builds are failing due to our good friend Twisted #9985 [1]:

    main function encountered error
    Traceback (most recent call last):
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
        _inlineCallbacks(None, g, status)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/treq/test/local_httpbin/child.py", line 175, in _serve_tls
        port = yield endpoint.listen(site)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/endpoints.py", line 1092, in listen
        interface=self._interface)
    --- <exception caught here> ---
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/treq/test/local_httpbin/child.py", line 175, in _serve_tls
        port = yield endpoint.listen(site)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/defer.py", line 122, in execute
        result = callable(*args, **kw)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/posixbase.py", line 521, in listenSSL
        tlsFactory = tls.TLSMemoryBIOFactory(contextFactory, False, factory)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/protocols/tls.py", line 773, in __init__
        contextFactory = _ContextFactoryToConnectionFactory(contextFactory)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/protocols/tls.py", line 651, in __init__
        oldStyleContextFactory.getContext()
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/_sslverify.py", line 1678, in getContext
        self._context = self._makeContext()
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/twisted/internet/_sslverify.py", line 1688, in _makeContext
        ctx.use_certificate(self.certificate)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/OpenSSL/SSL.py", line 865, in use_certificate
        _raise_current_error()
      File "/usr/lib/pypy3/lib_pypy/_functools.py", line 80, in __call__
        return self._func(*(self._args + fargs), **fkeywords)
      File ".../treq/.tox/pypy3-twisted_latest/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_use_certificate', 'ee key too small')]

[1]: https://twistedmatrix.com/trac/ticket/9985